sudo : required
services:
  - docker

before_install:
  - docker build -t ravi/dcoker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ravi/dcoker-react  npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dcoker-react"
  env: "DcokerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-097767552985"
  bucket_path: "dcoker-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"    